walter-cd/walter

README.md
=> Fix readme's typo.

README.md
=> correct shell_script by shell and shell _script by file into README.md

README.md, config/envvar.go, config/envvar_test.go, config/parser_test.go
=> Change the format of environment variables

stages/command_stage.go, stages/shell_script_stage.go
- the replaced environment variables information are logged with debug level for experimental use
Ref #85
=> Surpress the replaced envrionment variables in logging info

README.md, config/config_test.go, config/parser.go, config/parser_test.go, stages/base_stage.go, tests/fixtures/pipeline.yml
=> Simplify keys in the configuration file

config/parser.go, config/parser_test.go
=> Do not parse environment variables in command string

README.md, engine/engine_test.go, stages/command_stage.go
=> Support only_if

engine/engine.go, walter/walter.go
Small fix for typo in engine.go
=> Fixed typo in engine.go

README.md, config/parser.go, engine/engine.go, pipelines/pipeline.go, pipelines/pipeline_test.go, stages/base_stage.go, stages/command_stage.go, stages/stage.go
I add `report_full_output` flag to `stage` directive.
=> Report full output message with messenger feature

README.md, services/github.go
=> Filter pull requests by the name of their branches

messengers/slack.go
This PR colorize Slack notification like this:
=> Colorize Slack notification

stages/command_stage.go
This fix clear which stage the output from, especially when commands run in parallel.
=> Show stage name with command output

README.md, config/config.go, config/config_test.go, config/parser.go, config/parser_test.go, tests/fixtures/pipeline_with_require.yml, tests/fixtures/s1_stages.yml, tests/fixtures/s2_stages.yml, walter/walter.go
This pull request is for "include" feature discussed in #120. Before tackling the feature, I will do refactoring config.Parser to avoid spaghetti code.
=> Import predefined stages

build, config/parser.go, config/parser_test.go, messengers/fake.go, messengers/hipchat.go, messengers/hipchat2.go, messengers/messenger.go, messengers/slack.go, pipelines/pipeline.go, pipelines/pipeline_test.go
=> Suppress notification messages

config/envvar.go, config/parser.go, config/parser_test.go, engine/engine.go, engine/engine_test.go, log/glog_recorder.go, log/log.go, messengers/fake.go, messengers/hipchat.go, messengers/hipchat2.go, messengers/messenger.go, messengers/slack.go, pipelines/pipeline.go, pipelines/pipeline_test.go, services/github.go, services/github_test.go, services/local.go, services/service.go, stages/base_stage.go, stages/command_stage.go, stages/shell_script_stage.go, stages/stage.go, stages/test_sample.sh, stages/validator.go, version/version.go, walter/walter.go
hi @takahi-i this is remaining work of the minor formatting changes I started in #126. I had planned to add it after the previous pull request, but figured I add them anyway as a separate branch (i.e. this does NOT include the HCL changes in jacec-hcl branch).
Build and tests complete successfully.
Hope it helps, thanks!
=> minor changes to satisfy golint errors

build, test.sh
- download golint with go get
- apply golint in test.sh
- note: test.sh apply golint only when --lint parameter is given
Ref #133
=> Add checking with golint

build, engine/engine.go, wercker.yml
The code of this PR is equivalent to the original code, right ?
=> Tiny fix to simplify

build, config/envvar.go, config/parser.go, config/parser_test.go, engine/engine.go, engine/engine_test.go, main.go, messengers/hipchat.go, messengers/hipchat2.go, messengers/slack.go, pipelines/pipeline.go, pipelines/pipeline_test.go, services/github.go, services/service.go, stages/base_stage.go, stages/command_stage.go, stages/shell_script_stage.go, stages/validator.go, walter/walter.go
I've replaced `recruit-tech` with `walter-cd` because it's confusing.
@takahi-i Please check this.
=> Replace recruit-tech with walter-cd

stages/base_stage.go, stages/command_stage.go
It is useful to know how long each stage takes.
@takahi-i Please check this.
=> Set start and end time to each stage

README.md, build, stages/command_stage.go, stages/command_stage_test.go
=> Implementation wait_for

README.md, engine/engine_test.go
This patch contains the description and test case on square brackets in only_if attribute.
=> Added the description and test case on square bracket in only_if

engine/engine.go
This patch fixes #158
Test is https://github.com/walter-cd/walter-integration-test/commit/3003585f4e220a6c3d2dc864ade7bc0bfd93a483
=> Fix bug not to skip in parallel stages
