- services/github.go
This pull request adds the string `continuous-intgration/walter` on the build status like this.
> Add context string when updating github repo status

- README.md
- config/envvar.go
- config/envvar_test.go
- config/parser.go
- config/parser_test.go
Motivation is discussed in #67. 
The following is a sample the format of configuration files with environment variables.
Sample
=========
messenger:
type: ${env.MESSENGER_TYPE}
channel: ${env.SLACK_CHANNEL}
service:
type: github
token: ${env.GITHUB_KEY}
pipeline:
- stage_name: command_stage_1
stage_type: command
command: echo "hello, world"
run_after:
-  stage_name: command_stage_2_group_1
stage_type: command
command: echo "${JAVA_HOME}-desu"
-  stage_name: command_stage_3_group_1
stage_type: command
command: echo "hello, world, command_stage_3_group_1"
NOTE
==========
Environment variables are not supported in **block key** in the yaml formatted file.
For example, the following configuration is invalid
${env.BLOCKNAME} : command
> Support environment variables in the Walter configuration file

- config/config.go
- walter/walter.go
I fixed a runtime error, which occurs when the specified configuration file does not have **service** block.
17:03:23  INFO Not found "service" block
17:03:23  INFO local client was created
17:03:23  INFO Not found messenger block
17:03:23  INFO running Walter
17:03:23  INFO loading update file... ""
17:03:23  INFO opening file: ""...
17:03:23  WARN error occured opening file: "" ...
17:03:23  WARN open : no such file or directory
17:03:23  WARN continue the process with the new settings
17:03:23  INFO succeeded to load update file
17:03:23  INFO updating status...
17:03:23  INFO writing down new update: ""
17:03:23 ERROR failed to write update to file...: "open : no such file or directory"
17:03:23 ERROR failed to save status update
17:03:23  INFO more than one failures were detected …
> Fix runtime error when running walter without service block

- wercker.yml
Hi,
I have fixed output release tag step on werkcer .
If it's alright, please add tag after implementing the interesting features and release from the wercker.
F.Y.I. An auto deployment was success on my fork [higanworks/walter/releases](https://github.com/higanworks/walter/releases).
> Fix: avoid `Permission denied (publickey).` on wercker.

- wercker.yml
By this improvement, even after `git push` without release tag,  we can put git tag later and release by the tag with using `deploy to` wercker task.
**New release flow**
1. Merge this PR(only once)
2. Wait for passing wercker builds
3. Put release tag on latest commit-id with `git tag` command locally
4. Update remote tags on github with `git push --tags`
5. Kick `Deploy to` button on the wercker job corresponding to tagged commit-id
> Improve wercker release flow

- config/parser.go
- config/parser_test.go
- engine/engine.go
- engine/engine_test.go
- pipelines/pipeline.go
- pipelines/pipeline_test.go
- walter/walter.go
- created pipline.Resources
- moved reporters and channels to Resorces
> Refactoring pipeline and engine

- README.md
- config/parser.go
- config/parser_test.go
I've added the `parallel' config keyword to execute commands parallel. This is the implementation of #107 .
In this implementation, `parallel` is just an alias of `run_after` . But I think `parallel` is more understandable.
I've tested this code with this pipeline.yml.
```
pipeline:
- name: command 1
command: sleep 3
- name: parallel commands
parallel:
- name: parallel command 1
command: sleep 5
- name: parallel command 2
command: sleep 5
- name: command 2
command: sleep 3
```
Please check it.
> Implement `parallel' (just alias of run_after)

- README.md
I like fenced code blocks and it is easier to write than four spaces code blocks.
Also syntax hilighting works with fenced code blocks by specify the language like.
So I've fixed the README to use fenced code blocks instead of four spaces code blocks.
> Use fenced code blocks

- walter/walter.go
Current walter stop processing the pipelines in remaining pull requests when processing one of the pull requests or the head commit.
This patch make walter process **all the  pull requests** even when some of the pull requests failed.
> Make walter process remaining commits even when the current commit failed

- .gitignore
- README.md
- config/config.go
- services/github.go
- services/github_test.go
- services/service.go
- walter/walter.go
- added static constant DEFAULT_UPDATE_FILE_NAME (**.walter**)
- enhanced error handling when Walter configuration file does not exist in pull requests
- added elements to .gitignore
Ref #112
> Add default walter status file name

- messengers/slack.go
With this PR, you can set `icon_url` when notifying to Slack.
> Support icon_url of Slack incoming webhook

- engine/engine.go
- engine/engine_test.go
- pipelines/pipeline.go
- pipelines/pipeline_test.go
Walter reports skipped stage as "false" like this:
The result of **parallel command 1** is false, so the last stage **command 2** is skipped. But it's status is reported as **false**.
With this PR, Walter reports skipped stage as "skipped".
> Report skipped status as "skipped", not "false"

- config/config.go
- config/envvar.go
- config/parser.go
- engine/engine.go
- main.go
- messengers/fake.go
- messengers/hipchat.go
- messengers/hipchat2.go
- messengers/messenger.go
- messengers/slack.go
- pipelines/pipeline.go
- stages/base_stage.go
- stages/command_stage.go
- stages/shell_script_stage.go
- stages/stage.go
- walter/walter.go
> Add comments for godoc

- Godeps/Godeps.json
- README.md
- messengers/hipchat2.go
This pull request addresses https://github.com/walter-cd/walter/issues/47 by adding support for HipChat on-premises (private) servers to the `hipchat2` messenger by doing the following:
- bumping the godep for https://github.com/tbruyelle/hipchat-go to match upstream v1.0, which exposes BaseURL
- adding a configuration field to the hipchat2 messenger, `base_url`
- documenting the change in the README.md
The other `hipchat` messenger also supports BaseURL in their client, as of https://github.com/andybons/hipchat/commit/0fd4d621380d2b040f1ee141c8653f3fc7346484 but it has not been tagged as a release, so I did not include version 1 support.
I have verified this change works with our on-premises server.
> Add base_url support for hipchat2 private servers

- Godeps/Godeps.json
A clean build of walter following the README.md results in the following errors:
```
godep: Dep (github.com/stretchr/testify) restored, but was unable to load it with error:
Package (github.com/stretchr/objx) not found
godep: Dep (github.com/google/go-github/github) restored, but was unable to load it with error:
Package (github.com/google/go-querystring/query) not found
godep: Error checking some deps.
```
The version of godep built by walter was `godep v44 (linux/amd64/go1.4.2)`.  The problem can be reproduced using the following:
```
build@scdunlop ~/build> env  | grep '^GO'
build@scdunlop ~/build> git clone https://github.com/walter-cd/walter
Cloning into 'walter'...
remote: Counting objects: 1577, done.
remote: Total 1577 (delta 0), reused 0 (delta 0), pack-reused 1577
Receiving …
```
> update godeps.json to include missing dependencies

- stages/base_stage.go
- stages/command_stage.go
Without this code, `stage.Value.(*stages.CommandStage).GetReturnValue()` returns `false` even though the stage succeeded.
@takahi-i Please check this.
> Add BaseStage.SetReturnValue() to set return value

- services/github.go
- services/service.go
To jump to walter-server result page directly from GitHub, I've added `Url` field to `services.Result` and set this field value to `TargetUrl` of `github.RepoStatus` .
> Set TargetUrl to show the link to walter-server result page

- Godeps/Godeps.json
- services/github.go
Walter build fails because it depends on deprecated library (https://code.google.com/archive/p/goauth2/).
This patch fixes a build error.
> Replace OAuth libaries from deprecated one to fix a build error

- services/github.go
`go-github` can handle GitHub Enterprise by setting `github.Client.BaseURL` . So I made a change to set `github.Client.BaseURL` .
> Add BaseUrl to support GitHub Enterprise

- README.md
- config/envvar.go
- engine/engine.go
- pipelines/pipeline.go
- stages/base_stage.go
- stages/command_stage.go
- stages/stage.go
Most of CI tools (Jenkins, Wercker and so on) display the log without any distinction of stdout and stderr.
I'd like  walter-server to display the log in the same way.
This PR is for this purpose.
Also I've simplified the code to get stdout and stderr.
> Combine stdout and stderr

- stages/command_stage.go
`scanner.Scan()` returns "token too long" err if the command result is long.
Ref #153
> Use bufio.Reader instead of bufio.Scanner

- README.md
Why you made the change:
I did this so that people wouldn't accidentally copy and paste a broken
example.
> Fix small typo in the README.md
